
x-spring-profile: &spring-profile
  SPRING_PROFILES_ACTIVE: docker

services:
  gateway:
    build:
      context: ./api-gateway/api-gateway
      dockerfile: Dockerfile
    image: campo-vivo/gateway
    environment: *spring-profile
    ports:
      - "8080:8080"

  socios:
    build:
      context: ./ms-socios
      dockerfile: Dockerfile
    image: campo-vivo/socios
    environment: *spring-profile
    ports:
      - "8081:8081"

  hospedajes:
    build:
      context: ./ms-hospedajes
      dockerfile: Dockerfile
    image: campo-vivo/hospedajes
    environment: *spring-profile
    ports:
      - "8082:8082"

  huespedes:
    build:
      context: ./ms-huespedes
      dockerfile: Dockerfile
    image: campo-vivo/huespedes
    environment: *spring-profile
    ports:
      - "8083:8083"

  insumos:
    build:
      context: ./ms.insumos/ms.insumos
      dockerfile: Dockerfile
    image: campo-vivo/insumos
    environment: *spring-profile
    ports:
      - "8084:8084"

  actividades:
    build:
      context: ./ms-actividades
      dockerfile: Dockerfile
    image: campo-vivo/actividades
    environment: *spring-profile
    ports:
      - "8085:8085"

  productos:
    build:
      context: ./ms.productos/productos/productos
      dockerfile: Dockerfile
    image: campo-vivo/productos
    environment: *spring-profile
    ports:
      - "8086:8086"

  ventas:
    build:
      context: ./ms.ventas/ms.ventas/ms.ventas
      dockerfile: Dockerfile
    image: campo-vivo/ventas
    environment: *spring-profile
    ports:
      - "8087:8087"

  recursos:
    build:
      context: ./ms-recursos
      dockerfile: Dockerfile
    image: campo-vivo/recursos
    environment: *spring-profile
    ports:
      - "8088:8088"

  fondo:
    build:
      context: ./ms-fondo
      dockerfile: Dockerfile
    image: campo-vivo/fondo
    environment: *spring-profile
    ports:
      - "8089:8089"

  liquidaciones:
    build:
      context: ./ms-liquidaciones
      dockerfile: Dockerfile
    image: campo-vivo/liquidaciones
    environment: *spring-profile
    ports:
      - "8090:8090"