CREATE TABLE socio(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    socio VARCHAR(100) NOT NULL,
    predio VARCHAR(200) NOT NULL,
    capacidad NUMERIC(10) NOT NULL,
    estado VARCHAR(15) NOT NULL
);

INSERT INTO socio(socio, predio, capacidad, estado) VALUES ('Los Jackson', 'Parcela Los Alamos', 10, 'DISPONIBLE');
INSERT INTO socio(socio, predio, capacidad, estado) VALUES ('Los Molina', 'Fundo El carmen', 20, 'MANTENIMIENTO');
INSERT INTO socio(socio, predio, capacidad, estado) VALUES ('Los llanquitrue', 'Fundo Puerto Sofia', 15, 'SUSPENDIDO');


COMMIT;